apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
        - name: orderapp
          image: antoiner956/order_app:v1
          imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: Always
#          volumeMounts:
#            - name: mongodb-data
#              mountPath: /data/db
#            - name: mongodb-init-script
#              mountPath: /docker-entrypoint-initdb.d/init.js
#              subPath: init.js
#      volumes:
#        - name: mongodb-data
#          persistentVolumeClaim:
#            claimName: mongodb-data
#        - name: mongodb-init-script
#          configMap:
#            name: mongodb-init-script
