apiVersion: v1
kind: Service
metadata:
  name: orderapp
spec:
  selector:
    app: orderapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: http
      port: 27017
      targetPort: 27017
  type: ClusterIP
