version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: order_db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: orderdb
        ports:
            - 27017:27017
        volumes:
            - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
